### PR TITLE
[Fix #425] Fix a false positive for`Performance/StringIdentifierArgument

### LINKED ISSUE #425: The autocorrection for Performance/StringIdentifierArgument breaks code
## Expected behavior

The cop's autocorrection should not break code.

## Actual behavior

The cop's autocorrection breaks code.

## Steps to reproduce the problem

The following code runs:

```
# frozen_string_literal: true

module MyNamespace
  class MyClass
  end
end

prefix = 'MyNamespace::'
class_name = 'MyClass'
Kernel.const_get("#{prefix}#{class_name}")
```

Running rubocop on it transforms it to this:

```
# frozen_string_literal: true

module MyNamespace
  class MyClass
  end
end

prefix = 'MyNamespace::'
class_name = 'MyClass'
Kernel.const_get(:"#{prefix}#{class_name}")
```

Running the corrected code produces the following error:
```
app.rb:10:in `const_get': wrong constant name MyNamespace::MyClass (NameError)

Kernel.const_get(:"#{prefix}#{class_name}")
      ^^^^^^^^^^
	from app.rb:10:in `<main>'
```

## RuboCop version
```
1.59.0 (using Parser 3.2.2.4, rubocop-ast 1.30.0, running on ruby 3.1.1) [x86_64-linux]
  - rubocop-performance 1.20.0
```

### PR DESCRIPTION
**Pull request by Earlopain**
As per my findings in https://github.com/rubocop/rubocop-performance/pull/427#issuecomment-1865914939

I updated docs with string interpolation with an explicit example. It's not quite like the initial issue report where the colon came from the variable but it should get the point across.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop-performance/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/performance/string_identifier_argument.rb [hunk 1]
```diff
@@ -75,9 +83,14 @@ def string_arguments(node)
...
-            argument.str_type? || argument.dstr_type?
-          end
+          arguments.compact.filter { |argument| string_argument_compatible?(argument, node) }
+        end
+
+        def string_argument_compatible?(argument, node)
+          return true if argument.str_type?
+          return true if argument.dstr_type? && INTERPOLATION_IGNORE_METHODS.none? { |method| node.method?(method) }
+
+          false
```
Comment (koic) [inline lib/rubocop/cop/performance/string_identifier_argument.rb:93]:
```suggestion

          argument.dstr_type? && INTERPOLATION_IGNORE_METHODS.none? { |method| node.method?(method) }
```

File: spec/rubocop/cop/performance/string_identifier_argument_spec.rb [hunk 2]
```diff
@@ -44,15 +44,23 @@
...
-        expect_offense(<<~RUBY, method: method)
-          #{method}("do_something_\#{var}")
-          _{method} ^^^^^^^^^^^^^^^^^^^^^ Use `:"do_something_\#{var}"` instead of `"do_something_\#{var}"`.
-        RUBY
-
-        expect_correction(<<~RUBY)
-          #{method}(:"do_something_\#{var}")
-        RUBY
+      if RuboCop::Cop::Performance::StringIdentifierArgument::INTERPOLATION_IGNORE_METHODS.include?(method)
+        it 'does not register an offense when using string interpolation for `#{method}` method' do
```
Comment (koic) [inline spec/rubocop/cop/performance/string_identifier_argument_spec.rb:48]: Can you leave a text why this case is allowed?

**Comment by koic** [comment]
Thanks!
