### PR TITLE
[Fix #370] Fix an incorrect autocorrect for `Performance/RedundantMatch`

### LINKED ISSUE #370: Incorrect autocorrect for `Performance/RedundantMatch` cop
I've noticed that the cop's autocorrection is incorrect when using operators with lower precedence than `=~` as an argument to `match`.

Here's the reproducible code:

```ruby
arg = nil
puts "pass" if /regex/.match(arg || "default")
```

--------

## Expected behavior

To preserve the original behavior, parentheses should be added around the RHS.

```ruby
arg = nil
puts "pass" if /regex/ =~ (arg || "default")
```

This code produces no output.

## Actual behavior

Parentheses are missing, which results in the condition being evaluated as `(/regex/ =~ arg) || "default"`.

```ruby
arg = nil
puts "pass" if /regex/ =~ arg || "default"
```

This code outputs "pass".

## Steps to reproduce the problem

1. Save the provided code snippet into a file named `example.rb`.
2. Execute `bundle exec rubocop --only Performance/RedundantMatch -a example.rb`.

## RuboCop version

```
$ bundle exec rubocop -V
1.56.1 (using Parser 3.2.2.3, rubocop-ast 1.29.0, running on ruby 3.0.2) [
x86_64-linux]
  - rubocop-performance 1.19.0
  - rubocop-rspec 2.22.0
```

### PR DESCRIPTION
**Pull request by ymap**
Fixes #370.

This PR fixes an incorrect autocorrect for `Performance/RedundantMatch` when expressions with lower precedence than `=~` are used as an argument.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop-performance/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/performance/redundant_match.rb [hunk 1]
```diff
@@ -57,6 +59,35 @@ def autocorrectable?(node)
...
+            arg.source
+          end
+        end
+
+        def requires_parentheses?(arg)
+          return true if arg.if_type? && arg.ternary?
+          return true if arg.and_type? || arg.or_type? || arg.range_type?
+          return requires_parentheses_for_call_like?(arg) if call_like?(arg)
+
+          false
```
Comment (koic) [inline lib/rubocop/cop/performance/redundant_match.rb:78]: Can you refactor?

```suggestion
          call_like?(arg) && requires_parentheses_for_call_like?(arg)
```

File: lib/rubocop/cop/performance/redundant_match.rb [hunk 2]
```diff
@@ -57,6 +59,35 @@ def autocorrectable?(node)
...
+        end
+
+        def requires_parentheses_for_call_like?(arg)
+          return false if arg.parenthesized? || !arg.arguments?
+          return false if HIGHER_PRECEDENCE_OPERATOR_METHODS.include?(arg.method_name)
+
+          true
```
Comment (koic) [inline lib/rubocop/cop/performance/redundant_match.rb:85]:
```suggestion
          return false if arg.parenthesized? || !arg.arguments?

          !HIGHER_PRECEDENCE_OPERATOR_METHODS.include?(arg.method_name)
```

**Comment by ymap** [comment]
@koic Thanks for the suggestions! Amended the changes.

**Comment by koic** [comment]
Thanks!
